
on:
  push:
    branches:
    - main
    - dev

jobs:
  build-and-push:
    name: Build and Push on Dockerhub
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v6.17.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: khouloudbelkhir/mashup-game:latest



        
